strpcrlf ..\appgen\*.cpp /CR
strpcrlf ..\appgen\make* /CR
strpcrlf ..\appgen\*.h /CR
strpcrlf ..\bmp2vbm\*.cpp /CR
strpcrlf ..\bmp2vbm\make* /CR
strpcrlf ..\bmp2vbm\*.h /CR
strpcrlf ..\configs\*.mk /CR
strpcrlf ..\configs\*.txt /CR
strpcrlf ..\draw\*.cpp /CR
strpcrlf ..\draw\make* /CR
strpcrlf ..\draw\*.h /CR
strpcrlf ..\drawex\*.cpp /CR
strpcrlf ..\drawex\make* /CR
strpcrlf ..\drawex\*.h /CR
strpcrlf ..\examp\*.cpp /CR
strpcrlf ..\examp\make* /CR
strpcrlf ..\examp\*.h /CR
strpcrlf ..\iconed\*.cpp /CR
strpcrlf ..\iconed\*.h /CR
strpcrlf ..\iconed\make* /CR
strpcrlf ..\icons\*.cpp /CR
strpcrlf ..\icons\*.h /CR
strpcrlf ..\icons\make* /CR
strpcrlf ..\includew\v\*.h /CR
strpcrlf ..\includex\v\*.h /CR
strpcrlf ..\make* /CR
strpcrlf ..\srcwin\*.cpp /CR
strpcrlf ..\srcwin\make* /CR
strpcrlf ..\srcx\*.cxx /CR
strpcrlf ..\srcx\make* /CR
strpcrlf ..\srcx\*.c /CR
strpcrlf ..\test\*.cpp /CR
strpcrlf ..\test\*.h /CR
strpcrlf ..\test\make* /CR
strpcrlf ..\texted\*.cpp /CR
strpcrlf ..\texted\*.h /CR
strpcrlf ..\texted\make* /CR
strpcrlf ..\tutor\*.cpp /CR
strpcrlf ..\tutor\*.h /CR
strpcrlf ..\tutor\make* /CR
strpcrlf ..\vide\*.cpp /CR
strpcrlf ..\vide\*.h /CR
strpcrlf ..\vide\make* /CR
strpcrlf ..\vopengl\*.cpp /CR
strpcrlf ..\vopengl\*.h /CR
strpcrlf ..\vopengl\make* /CR
strpcrlf ..\vrefman\*.htm /CR
strpcrlf ..\vrefman\*.html /CR
